export const TEAM_LOGOS: Record<string, string> = {
  'Arsenal': 'https://resources.premierleague.com/premierleague/badges/t3.svg',
  'Aston Villa': 'https://resources.premierleague.com/premierleague/badges/t7.svg',
  'Bournemouth': 'https://resources.premierleague.com/premierleague/badges/t91.svg',
  'Brentford': 'https://resources.premierleague.com/premierleague/badges/t94.svg',
  'Brighton': 'https://resources.premierleague.com/premierleague/badges/t36.svg',
  'Brighton & Hove Albion': 'https://resources.premierleague.com/premierleague/badges/t36.svg',
  'Burnley': 'https://resources.premierleague.com/premierleague/badges/t90.svg',
  'Chelsea': 'https://resources.premierleague.com/premierleague/badges/t8.svg',
  'Crystal Palace': 'https://resources.premierleague.com/premierleague/badges/t31.svg',
  'Everton': 'https://resources.premierleague.com/premierleague/badges/t11.svg',
  'Fulham': 'https://resources.premierleague.com/premierleague/badges/t54.svg',
  'Leeds': 'https://resources.premierleague.com/premierleague/badges/t2.svg',
  'Leeds United': 'https://resources.premierleague.com/premierleague/badges/t2.svg',
  'Liverpool': 'https://resources.premierleague.com/premierleague/badges/t14.svg',
  'Man City': 'https://resources.premierleague.com/premierleague/badges/t43.svg',
  'Manchester City': 'https://resources.premierleague.com/premierleague/badges/t43.svg',
  'Man Utd': 'https://resources.premierleague.com/premierleague/badges/t1.svg',
  'Manchester United': 'https://resources.premierleague.com/premierleague/badges/t1.svg',
  'Newcastle': 'https://resources.premierleague.com/premierleague/badges/t4.svg',
  'Newcastle United': 'https://resources.premierleague.com/premierleague/badges/t4.svg',
  "Nott'm Forest": 'https://resources.premierleague.com/premierleague/badges/t17.svg',
  'Nottingham Forest': 'https://resources.premierleague.com/premierleague/badges/t17.svg',
  'Spurs': 'https://resources.premierleague.com/premierleague/badges/t6.svg',
  'Tottenham': 'https://resources.premierleague.com/premierleague/badges/t6.svg',
  'Tottenham Hotspur': 'https://resources.premierleague.com/premierleague/badges/t6.svg',
  'Sunderland': 'https://resources.premierleague.com/premierleague/badges/t56.svg',
  'West Ham': 'https://resources.premierleague.com/premierleague/badges/t21.svg',
  'West Ham United': 'https://resources.premierleague.com/premierleague/badges/t21.svg',
  'Wolves': 'https://resources.premierleague.com/premierleague/badges/t39.svg',
  'Wolverhampton': 'https://resources.premierleague.com/premierleague/badges/t39.svg',
  'Wolverhampton Wanderers': 'https://resources.premierleague.com/premierleague/badges/t39.svg'
};
